version: '3'

services:
    morpheus:
        build: .
        environment:
            - NEO4J_PEOPLE_URI=bolt://neo4j-people:7687
            - NEO4J_PEOPLE_USERNAME=neo4j
            - NEO4J_PEOPLE_PASSWORD=people
            - NEO4J_CARS_URI=bolt://neo4j-cars:7687
            - NEO4J_CARS_USERNAME=neo4j
            - NEO4J_CARS_PASSWORD=cars
            - NEO4J_INSURANCE_URI=bolt://neo4j-insurance:7687
            - NEO4J_INSURANCE_USERNAME=neo4j
            - NEO4J_INSURANCE_PASSWORD=insurance
        ports:
            - 8888:8888
            - 4040:4040
        volumes:
            - ./src:/home/jovyan/work
        networks:
            - magicworld
    neo4j-people:
        image: neo4j:3.5.17
        hostname: neo4j-people
        environment:
            - NEO4J_AUTH=neo4j/people
        ports:
            - 7474:7474
            - 7687:7687
        networks:
            - magicworld
    neo4j-cars:
        image: neo4j:3.5.17
        hostname: neo4j-cars
        environment:
            - NEO4J_AUTH=neo4j/cars
            - NEO4J_dbms_connector_bolt_advertised__address=:7688
        ports:
            - 7475:7474
            - 7688:7687
        networks:
            - magicworld
    neo4j-insurance:
        image: neo4j:3.5.17
        hostname: neo4j-insurance
        environment:
            - NEO4J_AUTH=neo4j/insurance
            - NEO4J_dbms_connector_bolt_advertised__address=:7689

        ports:
            - 7476:7474
            - 7689:7687
        networks:
            - magicworld

networks:
    magicworld: